spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL_POSTGRES:url:jdbc:postgresql://localhost:5432/videos?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:mx123mx}
    driverClassName: org.postgresql.Driver



    